CREATE TABLE TITLES (
    TITLE_ID VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    PRIMARY KEY (TITLE_ID)
);

CREATE TABLE EMPLOYEES (
    EMP_NO INT NOT NULL,
    EMP_TITLE_ID VARCHAR NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    SEX VARCHAR NOT NULL,
    HIRE_DATE DATE NOT NULL,
    PRIMARY KEY (EMP_NO)
    FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES(TITLE_ID)
);


CREATE TABLE DEPARTMENTS (
    DEPT_NO VARCHAR NOT NULL,
    DEPT_NAME VARCHAR NOT NULL,
    PRIMARY KEY (DEPT_NO)
);

CREATE TABLE DEPT_MANAGER (
    DEPT_NO VARCHAR NOT NULL,
    EMP_NO INT NOT NULL,
    FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO),
    FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
    PRIMARY KEY (EMP_NO, DEPT_NO)
);

CREATE TABLE DEPT_EMP (
    EMP_NO INT NOT NULL,
    DEPT_NO VARCHAR NOT NULL,
    FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO),
    FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
    PRIMARY KEY (EMP_NO, DEPT_NO)
);


CREATE TABLE SALARIES (
    EMP_NO INT NOT NULL,
    SALARY INT NOT NULL,
    FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
	PRIMARY KEY (EMP_NO)
);
